### ISSUE TITLE
Gitlab private repo

### ISSUE THREAD

**Issue by whoami213** [codedge/laravel-selfupdater#111]
Please add a support for gitlab repository.
as of not the available is http and github only.

Thanks

**Comment by scramatte** [comment]
Hello @codedge ,

i may can get you an hand. We have already setup our own private gitlab. We can sponsor the dev and/or I can’t help you with my pho knowledge. Contact me to discuss details 

regards

**Comment by z3d0** [comment]
+1
@codedge any chance you’re gonna plan this implementation in the short term?
Thanks a lot

**Comment by codedge** [comment]
@scramatte Sorry for being late here. If you want to sponsor this, just go on, even some small amount helps :) Happy to implement this

**Comment by scramatte** [comment]
@codedge , sorry for late reply too.  Does it posible to implement gitea private repository too?  Gitlab requires  quite a lot of resources  and  knowledge to maintained  compared to gitea.  Anyways it would be nice to have support for both.

**Comment by codedge** [comment]
I think this is also possible. I don't have a Gittea instance runnning. So if you can provide one to seet the API response I could check what needs to be done.

**Comment by scramatte** [comment]
@codedge , I'm going to prepare you gitea repository for testing. 
I've just  sponsor you.  Thank you to make  so useful tool available for whole Laravel users community

**Comment by z3d0** [comment]
@codedge  I've sponsored too for the Gitlab version :)
Thank you!

**Comment by codedge** [comment]
@z3d0 You might want to check out version 3.4 - support for Gitlab is ready.

For this to work, you need to create a release for your project in Gitlab and tag it.

**Comment by codedge** [comment]
@scramatte Please open a separare ticket for Gitea. Thanks you!
