### ISSUE TITLE
[Enhancement] Support Composer Install / Update

### ISSUE THREAD

**Issue by whoami213** [codedge/laravel-selfupdater#112]
Please add `composer update/install` after/before the update, this will help for new vendor added on the system updates.

This will help alot!

thanks

**Comment by turbo124** [comment]
@whoami213 you can manage this using the post hooks already built into the self updater, we have the following job in the post_update method.
 
https://github.com/invoiceninja/invoiceninja/blob/5bb7f70bdff09062b2bb70f57daec2668838f6af/app/Console/Commands/PostUpdate.php#L1
