### ISSUE TITLE
How and where to set download path?

### ISSUE THREAD

**Issue by filippetrovicAT** [codedge/laravel-selfupdater#114]
![Unbenannt](https://user-images.githubusercontent.com/65421448/82879271-01308580-9f3d-11ea-9c5c-b3aac5076373.PNG)
In the picture above you can see the a folder called "netbounty-shop-52f688b". In there is my fresh downloaded repo. How the heck do I grab all the files and replace them with my original or is there any known bug? Or do I have to change my download path to replace them right?

**Comment by codedge** [comment]
Your download folder should not be inside the folder your app lives, as it might be overwritten during the update.

```
/my-app
  | -- fileA
  | -- ...
/folder-for-download
  | -- my-net-version-archive.zip
```
