### ISSUE TITLE
Not using bearer token for Github

### ISSUE THREAD

**Issue by paumove** [codedge/laravel-selfupdater#115]
I have configured everything to access a private repository using a token, but calling "getVersionAvailable" returns the following error: 404 Not Found.

As I see in the code, the token is not being used in the request. If I make the following change it works correctly:

Class GithubTagType
Method getRepositoryReleases
Lines from 122 to 126
```
//if ($this->hasAccessToken()) {
        $headers = [
            'Authorization' => "Bearer <token>", //$this->getAccessToken(),
        ];
//}
```

Thanks for your support.

**Comment by johnnybaida** [comment]
I also have the same problem. When will it be integrated into the master branch?

Thanks for your support.

**Comment by codedge** [comment]
Thanks for the hint. I'll check.
