### ISSUE TITLE
Updating from wrong release folder

### ISSUE THREAD

**Issue by PunyFlash** [codedge/laravel-selfupdater#179]
I found a major issue when new release folder is created. This line is actually not working as such release folder already exists:

https://github.com/codedge/laravel-selfupdater/blob/5fbe16f3622c119c7279d69400690e6b927dbf01/src/Models/Release.php#L267

As a result there are 2 folders created and app tries to update from wrong folder (`0.0.1`, but files are being stored in `0.0.12021-03-19`):
![image](https://user-images.githubusercontent.com/14828695/111831288-cfd3dc80-88f7-11eb-9253-a90dec30a44a.png) ![image](https://user-images.githubusercontent.com/14828695/111831379-f72aa980-88f7-11eb-9e15-dacf9f07b662.png)

Adding `$force = true` parameter to `moveDirectory` method fixed issue for me:

```php
$this->filesystem->moveDirectory(
    createFolderFromFile($this->getStoragePath()).now()->toDateString(),
    createFolderFromFile($this->getStoragePath()),
    true
);
```

**Comment by codedge** [comment]
Fixed in https://github.com/codedge/laravel-selfupdater/commit/ade06363a1a8175adcf070f392f1fd25eef5c214
