### ISSUE TITLE
checkPermissions($this->basePath) is false so can't update

### ISSUE THREAD

**Issue by Mathsyo** [codedge/laravel-selfupdater#288]
Hi, 

I would like to purpose an update button to my admin dashboard for my laravel project.
But, when a new version is available, I click on the update button and nothing.
So I analyzed and found that the problem is in the "UpdateExecutor" class :
this function "checkPermissions($this->basePath)" return false so i can't update.

What I missed ? I don't understand..

Math_syo.

**Comment by codedge** [comment]
So probably the base path is not writeable. This means that the root directory of your application does not seem to be writeable or one of the files inside the root directory (it checks it recursivly) is not writeable.
