### ISSUE TITLE
Downloading updates from http source doesnt work

### ISSUE THREAD

**Issue by XiDanko** [codedge/laravel-selfupdater#309]
when trying to download a release i get this error
`cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http:update-server.localhostv1.0.1.zip`
this is my env

SELF_UPDATER_VERSION_INSTALLED=1.0
SELF_UPDATER_SOURCE=http
SELF_UPDATER_PKG_FILENAME_FORMAT=v_VERSION_
SELF_UPDATER_REPO_URL=http://update-server.localhost/
SELF_UPDATER_DOWNLOAD_PATH=/tmp

it looks like your regular expression is deforming the repo url

**Comment by codedge** [comment]
Can you show the complete output, the complete error message including stack trace?

**Comment by 0ofland** [comment]
I got the same error when using http source, thought I'd post here instead of opening a new issue.

Here's the  error message, and stack trace: 
https://flareapp.io/share/NPL92qg7#F60

**Comment by 0ofland** [comment]
Is there a way to use a GitHub release as the update source instead of the repository itself?

**Comment by codedge** [comment]
Hmm.. sorry for the late response. There seems to be sth. weird with detecting the correct url. It would be nice to see what the output/response of your `repository_url` is that you specified via env var or in `config/self-updater.php`.

**Comment by codedge** [comment]
> Is there a way to use a GitHub release as the update source instead of the repository itself?
What do you mean whith that?

For GitHub, you can select a branch to update from or a release/tag.

**Comment by codedge** [comment]
@0ofland @XiDanko 

I found the issue and working on some fixes.
