### ISSUE TITLE
Make the download directory configurable instead of using hardcoded /tmp

### ISSUE THREAD

**Issue by staegi** [codedge/laravel-selfupdater#320]
My domain hosting is not allowing to use /tmp and I need to choose another directory to download the installation files. Please provide the capability to make the folder configurable

**Comment by codedge** [comment]
I think this is already configurable - [see in config](https://github.com/codedge/laravel-selfupdater/blob/master/config/self-update.php#L45).

You can use the env var `SELF_UPDATER_DOWNLOAD_PATH`
