### ISSUE TITLE
add support for gitea

### ISSUE THREAD

**Issue by scramatte** [codedge/laravel-selfupdater#352]
Hi,

Can you please add support for gitea

Regards

**Comment by codedge** [comment]
@scramatte You wanted to provide a testing instance with that I can play around. Is that still valid? I don't find time to install it.

**Comment by scramatte** [comment]
Hello,

I’m going to prepare you a gitea instance. Let me a couple of days
Regards



De: Holger Lösken ***@***.***>
Responder a: codedge/laravel-selfupdater ***@***.***>
Fecha: lunes, 9 de mayo de 2022, 10:17
Para: codedge/laravel-selfupdater ***@***.***>
CC: * * ***@***.***>, Mention ***@***.***>
Asunto: Re: [codedge/laravel-selfupdater] add support for gitea (Issue #352)


@scramatte<https://github.com/scramatte> You wanted to provide a testing instance with that I can play around. Is that still valid? I don't find time to install it.
