### ISSUE TITLE
No release found for version

### ISSUE THREAD

**Issue by DuelistRag3** [codedge/laravel-selfupdater#354]
When i hit my update button i get
` No release found for version "0.5.0". Please check the repository you're pulling from.`
My version_installed is set to v.0.6 and my latest tag is v.0.7
what am i doing wrong?

all my tags:
![image](https://user-images.githubusercontent.com/23101343/167034667-cf889acd-534c-4d78-8a69-97c9b2d530e9.png)

**Comment by KevinEduardo** [comment]
I also wanna know about this. Kinda having the same issue here.

**Comment by DuelistRag3** [comment]
> I also wanna know about this. Kinda having the same issue here.

Have you changed your repo url and forgot to change vendor and repose tory name? That was my issue, vendor has to be your account name where the repository is and repostery name is obviously the name of the repo

**Comment by codedge** [comment]
@DuelistRag3 

Your installed version is `0.6` but you try to update to version **`0.5.0`** - see the error`No release found for version "0.5.0"`.

... and obviously you have a higher version installed (`0.6`) than `0.5.`.

Don't specify the version you want to update to and just let the updater pick the most recent version.

**Comment by DuelistRag3** [comment]
> @DuelistRag3 
> 
> Your release is named `v.0.5.`. In the error message I cannot see a `v` and I see `0.5.0` with the `0` ending.
> Please speacify exactly the version.

That wasn't exactly the issue, I moved the repo once and only changed the url and not the vendor and the name and I used different versioning on the other repo

**Comment by codedge** [comment]
Ah ok. So is it solved now?

**Comment by DuelistRag3** [comment]
> Ah ok. So is it solved now?

Yes, I'll close
