### ISSUE TITLE
add support for laravel 9

### ISSUE THREAD

**Issue by rezahmady** [codedge/laravel-selfupdater#365]
please add support for laravel 9 👌🚩

**Comment by codedge** [comment]
Sorry for the late reply but this package is installable with Laravel 9.

What you see:
- Fresh install of Laravel 9
- Check `composer.json` to verify that it really is Laravel 9
- Require this package -> Can be installed ✔️ 

![2022-07-17 at 11 38 56](https://user-images.githubusercontent.com/4409904/179392595-cfbb5ca1-a455-4f2a-b237-81b490def61f.gif)

**Comment by pixelated-au** [comment]
Hi, I'm not sure how you managed to get this installed in Laravel 9. Your composer.json file is version locked to Laravel 8 🤷‍♂️
`"laravel/framework": "^8.83.23",`

I definitely can't get it installed on L9. I'll fork it to get it operational for now 👍
