### ISSUE TITLE
Running migration commands

### ISSUE THREAD

**Issue by alexcroox** [codedge/laravel-selfupdater#39]
Would running any artisan commands such as db migrations be on your roadmap?

**Comment by codedge** [comment]
Hi @alexcroox,
you mean running an `artisan` command before or after an update process? I never thought about this, but that's a good point.

I'll check and would implement sth.

Thanks for the idea!

**Comment by alexcroox** [comment]
That's right, I'm distributing an open source Laravel app and ideally I want for users to be able to easily install and update on hosts where they may not have SSH access.
