### ISSUE TITLE
Call to undefined method Codedge\Updater\Events\UpdateSucceeded::getVersionAvailable()

### ISSUE THREAD

**Issue by dvidke** [codedge/laravel-selfupdater#41]
Hello!

Could you help me in this error?

http://imgur.com/a/rRIfL

What u need to know:

- Fresh laravel install
- My web.php route: http://imgur.com/a/94DBr
- Everything else is configured by your guide

The update is running properly, but i always get this message and ofc i can not recieve the email.

Thanks for your help!

p.s: This package isn't removing files if those aren't exist anymore in the new release, am i right? Or is there any way to do that? 

p.s 2: Something is wrong with your contact form on your page: https://codedge.de/ (execution timeout, after sending a message). That's why i wrote my issue here :(

**Comment by codedge** [comment]
Thanks for the hint! I'll have a look into it tmrw.

**Comment by muyaedward** [comment]
Hey @codedge was this issue resolved. I have the same issue here

**Comment by AndrewAubury** [comment]
same

**Comment by codedge** [comment]
Please try the new major version 3.0. The problem should be solved.
