### ISSUE TITLE
 cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MarJose123** [codedge/laravel-selfupdater#413]
encountered an issues on my local development

**Comment by MarJose123** [comment]
I found a temporarily solution by using this
https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)

**Comment by codedge** [comment]
That has certainly nothing to do with this lib.
