### ISSUE TITLE
Github private repo access

### ISSUE THREAD

**Issue by bhanu2217** [codedge/laravel-selfupdater#42]
Is it possible to use this code with Github Private repository also?

I would like to check in user has valid subscription with us and if yes, give him access to upgrade to the latest release. Don't want to give permanent access to private repository but temporary to download the release.

**Comment by noxify** [comment]
I think it's already possible.

Create your own repository type, which has a response the zip archive with the latest version.
Via a a config attribute, you can define a API token or something like that, to verify that only valid users can fetch the latest version (or whatever you want).

**Comment by vortechron** [comment]
@codedge should add default support for private repos using access_token in config.

**Comment by ahkmunna** [comment]
Can anyone tell me how to configure GitHub private repo?

**Comment by potreco** [comment]
Any news about it?

**Comment by codedge** [comment]
No, currently not. I have too less time to implement. If anyone wants to open a PR I am happy to check and merge.

**Comment by prg-hussam** [comment]
Any news about it?

**Comment by codedge** [comment]
I added support for private repositories via Bearer Tokens: https://github.com/codedge/laravel-selfupdater#private-repositories.

There is now a `private_access_token` field inside the [config file](https://github.com/codedge/laravel-selfupdater/blob/master/config/self-update.php#L46).
