### ISSUE TITLE
Can’t fetch repo from github

### ISSUE THREAD

**Issue by ruaq** [codedge/laravel-selfupdater#421]
If I’m trying to fetch a repo from github with

```
$versionAvailable = $updater->source()->getVersionAvailable();
$release = $updater->source()->fetch($versionAvailable);
```

I get a `Illuminate \ Http \ Client \ ConnectionException` with the message:

`cURL error 6: Could not resolve host: repos (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for repos/courservio/courservio/zipball/aa49aacc7fa61de8d9135a65c9cc9c0980a6e387`

My config in .env is

```
SELF_UPDATER_REPO_VENDOR=courservio
SELF_UPDATER_REPO_NAME=courservio
SELF_UPDATER_USE_BRANCH=self-update
SELF_UPDATER_VERSION_INSTALLED=2020-04-19T22:35:48Z
```

Using PHP 8.1.14, Laravel 9.48.0
The `installedVersion` is `2020-04-19T22:35:48Z` and the `versionAvailable` is `2023-01-29T00:22:28Z`.

`self-update.php` wasn't changed.

I figured out, that the `download()` function in `Release.php` is missing the host (api.github.com) but not why. Using tags works fine.

What am I missing?

**Comment by codedge** [comment]
Hmm..good catch. This seems to be a bug with **branch-based releases**. I am going to have a look.

**Comment by ruaq** [comment]
OK, I wasn’t sure if I missed something. ;-) #422 should fix it if you want to use it.
