### ISSUE TITLE
Excluding vendor directory

### ISSUE THREAD

**Issue by alexcroox** [codedge/laravel-selfupdater#43]
Just getting setup, I noticed `'exclude_folders' => ['vendor']`. Is it best practice would you say to not distribute /vendor and run `composer update`? Can this even be done with `post_update`? I thought that was for artisan commands only? Thanks.

**Comment by codedge** [comment]
I always go for the approach of excluding the `vendor` folder and run `composer update` instead. What do you mean with `post_update` - the `post-update-cmd` in `composer.json`?

**Comment by alexcroox** [comment]
For post_update I was referring to the config:

![ss](https://cl.ly/mZOY/Screen%20Shot%202017-09-18%20at%2013.18.37.png)

Not sure where else I could put `composer update` so it's run after the system updates itself?

**Comment by codedge** [comment]
Yes, the `post_update` section is a good place to run the `composer update` command.
