### ISSUE TITLE
Config is not published

### ISSUE THREAD

**Issue by freescout-helpdesk** [codedge/laravel-selfupdater#49]
Laravel 5.5
Self-Updater 1.4.3
PHP 7.2.11

Config is not published when running command:
```
php artisan vendor:publish --provider="Codedge\Updater\UpdaterServiceProvider"
```

Other packages are successfully publishing their configs.

Is it Laravel 5.5 compatible?

**Comment by freescout-helpdesk** [comment]
Copied manually `self-updater.php`, now when doing `Updater::isNewVersionAvailable('1.2')`:

> Call to undefined method Codedge\Updater\UpdaterManager::isNewVersionAvailable()

**Comment by freescout-helpdesk** [comment]
In the readme this
```
'aliases' => [
        // ...
        
        'Updater' => Codedge\Updater\UpdaterManager::class, // [2]
```
should be changed to

```
'aliases' => [
        // ...
        
        'Updater' => Codedge\Updater\UpdaterFacade::class, // [2]
```

**Comment by codedge** [comment]
I cannot reproduce the issues.

```shell
$ -> php artisan vendor:publish --provider="Codedge\Updater\UpdaterServiceProvider"
Copied File [/vendor/codedge/laravel-selfupdater/config/self-update.php] To [/config/self-update.php]
Copied Directory [/vendor/codedge/laravel-selfupdater/resources/views] To [/resources/views/vendor/self-update]
Publishing complete.
```
... and the files are actually there. 

The readme is changed. Thanks for the hint.
