### ISSUE TITLE
5.8 support

### ISSUE THREAD

**Issue by robertnicjoo** [codedge/laravel-selfupdater#50]
Hi,
Does it work on laravel 5.8?

**Comment by codedge** [comment]
I did not try yet, but I expect that it does.
I can try today and let you know.

**Comment by robertnicjoo** [comment]
@codedge i would be appreciate it.

**Comment by steve-ks** [comment]
As I worked on a PR during the last two days I was testing the Package using Laravel 5.8. At least using not Github but another repository type (HttpRepositoryType as used within the PR) everything worked properly. For Github itself I cannot tell if it is working as expected.

**Comment by codedge** [comment]
@steve-ks Nice, thanks for the info. I think updating from Github or another repository type is not the question.
Thanks for the PR. Looks good 👍 


@robertnicjoo You mean if you can use this package with a Laravel 5.8 installation, right?

**Comment by robertnicjoo** [comment]
@codedge yes i need to install it on laravel 5.8 

Ps: if steve pr is working probably you need to update readme file "Compatible" part.

Thanks

**Comment by codedge** [comment]
@robertnicjoo the current package version 2.1 works without issues with Laravel 5.8.
Can you point me to the section that is wrong in the readme? .. the "compatible" part?

**Comment by robertnicjoo** [comment]
Thank you i will test it then.

Apparently you already edit readme file.

Before had ``5.x`: Compatible with PHP 5.5 + 5.6` sentence.

**Comment by codedge** [comment]
Yes, that was only pointing to the _PHP version_ not the _Laravel version_ :)
