### ISSUE TITLE
Composer not fetching latest version

### ISSUE THREAD

**Issue by Jas-n** [codedge/laravel-selfupdater#508]
Hello,

I'm trying to update to Laravel 11, but composer isn't pulling from the master branch.

[Packagist](https://packagist.org/packages/codedge/laravel-selfupdater), shows the Laravel 11 stuff is on dev-master, not a versioned release.

Any chance you could update?

Thank you.

**Comment by codedge** [comment]
@Jas-n Totally right. I released a new version... 3.8.2.

**Comment by Jas-n** [comment]
Thanks again
