### ISSUE TITLE
QUESTION: how does the update actually work?

### ISSUE THREAD

**Issue by itsmenewbie03** [codedge/laravel-selfupdater#509]
I tried implementing a self update feature on my project but ended up reverting it as I can't seem to see how it does the update?
I was able to complete the setup but for some reason the getAvailableVersion does not return the latest release but it does reflect if I use the getReleases function. I tried reading the readme over and over but no luck still I don't understand how it does the self update.

**Comment by richard-muvirimi** [comment]
First of all, are you using semantic versioning, secondly this new release, are you sure it does not have any white space? Which source are you using for the updates?
