### ISSUE TITLE
getVersionAvailable() throws exception if http repo is empty

### ISSUE THREAD

**Issue by Autoflow** [codedge/laravel-selfupdater#83]
In my usecase i have version 1.0 running and have no updates in repo yet. 
My question is if throwing an exception ("Retrieved version list is empty.") in this case a good idea? 
As user i would expect isNewVersionAvailable() to return "false".

Thanks for the great work on this project ..

**Comment by codedge** [comment]
Good, point and right, then the `isNewVersionAvailable` should return `false`. Would you be able to create a PR?
