### ISSUE TITLE
Support for incremental updates

### ISSUE THREAD

**Issue by Autoflow** [codedge/laravel-selfupdater#87]
Just figured out that i need incremental updates for http repos.

Example: if http repo contains multiple update archives like

- myproject_v1.0.1.zip
- myproject_v1.0.2.zip 
- myproject_v1.0.3.zip
- ...

all zip files beginning from SELF_UPDATER_VERSION_INSTALLED should be installed one after another.

`    if($updater->source()->isNewVersionAvailable()) {

        // Get all the newest versions available
        $updater->source()->getVersionsAvailable();

        // Run the update process for all zip files
        $updater->source()->updateIncrementing();
`

Would this be s.th. for you?

**Comment by codedge** [comment]
And what if you just pull them one by one? Starting with 1.0.1, then 1.0.2 and after that 1.0.3. I currently do not see the benefit of pulling them all at once.
