### ISSUE TITLE
cURL error 3: <url> malformed (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by turbo124** [codedge/laravel-selfupdater#92]
Since latest update, seeing this error when calling $updater->update();

**Comment by codedge** [comment]
On it. I am in the middle of a bigger update. Will finish this till the weekend.

**Comment by codedge** [comment]
The fastes is probably lock the version to `2.5.1`. I am going to need to finish a couple of things and then release a bigger change as a separate major release. Would that be ok for you?

**Comment by codedge** [comment]
Please see latest major version [3.0](https://github.com/codedge/laravel-selfupdater/releases/tag/3.0). The issue should be gone now.

ℹ️ See the [new usage](https://github.com/codedge/laravel-selfupdater#usage) instructions how to run an update.

**Comment by turbo124** [comment]
Fixed! thanks!
